[package]
name = "minigrep"
version = "0.1.0"
authors = ["Berm MBA11 <berm@mba11.mac>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
